---

gitlab:
  address: gitlab
  port: 8080
  tls: ~

cache:
  ttl: 30s

realms:
  '': # default realm
    - &common_acls
      reject_locked: true
      reject_dormant: true
      reject_pristine: true
  enclave: # multiple authz conditions
    # require 2FA set up
    - require_2fa: true
      <<: *common_acls
    # OR members of admin group
    - require_groups: [ core:admins ]
      <<: *common_acls
  lockdown: [] # noone is getting in

health:
  port: 18080

metrics:
  port: 9080

profile:
  port: 4380

web:
  path: ./web


